apiVersion: v1
kind: PersistentVolume
metadata:
  name: kebsvol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-066711b1814dcae66 (kamal-k8s-pv)           # YAHAN APNI EBS VOLUME ID DAALO
    fsType: ext4
